version: '3'
services:
  na-service:
    build: na-service
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-service
    ports:
      - 8090:8090
volumes:
  na-mysql-data:
networks:
  default:
    external:
      name: "na"
