version: '3.5'
services:
  na-service:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/bepicky.na-service
    environment:
      - MYSQL_NA_DB=${MYSQL_NA_DB}
      - MYSQL_NA_USER=${MYSQL_NA_USER}
      - MYSQL_NA_PASSWORD=${MYSQL_NA_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 5s
      retries: 3
    ports:
      - 8080:8080
networks:
  default:
    external:
      name: picky
