version: '3.5'
services:
  na-service:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-service
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_NA_DB=${MYSQL_NA_DB}
      - MYSQL_NA_USER=${MYSQL_NA_USER}
      - MYSQL_NA_PASSWORD=${MYSQL_NA_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}
    ports:
      - 8080:8080
networks:
  default:
    external:
      name: picky
