version: '3.5'
services:
  na-service:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-service
    environment:
      - MYSQL_NA_DB=${MYSQL_NA_DB}
      - MYSQL_NA_USER=${MYSQL_ROOT_USER}
      - MYSQL_NA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - 8090:8090
volumes:
  na-mysql-data:
networks:
  default:
    external:
      name: picky
