na:
  reader:
    tag:
      limit: -1
  schedule:
    read:
      enabled: true
    sync:
      enabled: true
      cron: '*/10 * * * * *'
    notify:
      enabled: true
      limit: 3
      cron: '0/10 * * * * *'
    webpagereader:
      cron: '0 */1 * * * *'
      timeout: 20
    archive:
      cron: '0 0 */1 * * *'
      months: 3