na:
  reader:
    tag:
      limit: -1
  schedule:
    parse:
      enabled: true
      timeout: 30
    sync:
      enabled: true
      cron: '*/10 * * * * *'
    notify:
      enabled: true
      limit: 3
      cron: '0/10 * * * * *'
    archive:
      cron: '0 0 */1 * * *'
      months: 3