na:
  reader:
    tag:
      limit: 50
  schedule:
    read:
      enabled: true
      cron: '*/10 * * * * *'
    sync:
      enabled: true
      cron: '0 * * * * *'
    notify:
      enabled: true
      limit: 3
      cron: '* */2 * * * *'
    archive:
      cron: '0 0 0 */1 * *'
      months: 18