server:
  port: 8080
database:
  ddl-file: src/main/resources/db/migration/V1__init.sql
spring:
  application:
    name: bepicky-service
  main:
    banner-mode: "off"
  config:
    import: "optional:"
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_SELF_REFERENCES: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://na-database:3306/${MYSQL_NA_DB}?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_NA_USER}
    password: ${MYSQL_NA_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    hostName: na-service
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://na-registry:8761/eureka/
logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
topics:
  category:
    cmd: category.cmd.start
    list: category.list.start
  lang:
    cmd: lang.cmd.start
  message:
    text: msg.txt
  reader:
    notification: reader.notification
  news:
    notification:
      new: newsnote.notification
      success: newsnote.notification.success
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace