na:
  reader:
    tag:
      limit: -1
  schedule:
    parse:
      enabled: true
    sync:
      enabled: true
      cron: '0 * * * * *'
    notify:
      enabled: true
      limit: 3
      cron: '0/10 * * * * *'
    archive:
      cron: '0 0 */1 * * *'
      months: 3
    enable-sleepers:
      cron: '0 0 */1 * * *'