na:
  reader:
    tag:
      limit: 50
  schedule:
    parse:
      enabled: true
    sync:
      enabled: true
      cron: '0 */19 * * * *'
    notify:
      enabled: true
      limit: 5
      cron: '0 */10 * * * *'
    archive:
      cron: '0 0 0 */1 * *'
      months: 18