version: 2.1
workflows:
  build:
    jobs:
      - build-deploy:
          context: DEPLOY
jobs:
  build-deploy:

    working_directory: ~/na-service

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - add_ssh_keys:
          fingerprints:
            - "5f:5f:ed:4e:9b:5e:75:59:92:00:36:64:3a:95:13:6b"
      - setup_remote_docker

      - restore_cache:
          keys:
            - na-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: na-service-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - run:
          name: docker-compose
          command: |
            set -x
            docker network create na
            docker-compose --project-name na -f docker-compose.yml up --build --no-start na-service

      - run:
          name: docker login
          command:
            echo "$GITHUB_TOKEN" | docker login https://docker.pkg.github.com --username $GITHUB_USER --password-stdin

      - run:
          name: docker push
          command: docker push docker.pkg.github.com/news-aggregator-bot/artifactory/vlad110kg.na-service:latest

      - deploy:
          name: deploy image to remote
          command: ssh -i $SSH_USER@$SSH_HOST "/bin/bash --login -s" -- < scripts/swarm-update.sh "https://raw.githubusercontent.com/news-aggregator-bot/service/master/docker-compose.yml"