name: na-service Docker Image

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker-compose
      run: set -x
            docker network create picky
            docker-compose --project-name na -f docker-compose.yml -f docker-compose.dev.yml up --build --no-start na-service
  
