name: na-service Docker Image

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -s .github/settings.xml dependency:go-offline package
      
    - name: create network
      run: set -x && docker network create picky
    - name: build image
      run: docker-compose --project-name na -f docker-compose.yml -f docker-compose.dev.yml up --build --no-start na-service
    - name: push image
      run: docker push ghcr.io/news-aggregator-bot/bepicky.na-service:latest

  
